# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
image:
  file: .gitpod.Dockerfile

tasks:
  - name: Setup Python
    command: |
      python3.8 -m venv venv
      . venv/bin/activate
      pip install --upgrade pip
      pip install -r requirements.txt

# 配置启动时的命令
ports:
  - port: 8000
    onOpen: open-preview
